name: artifacts
on:
  workflow_dispatch:
jobs:
  download-artifact:
    name: job to download and test the artifact
    runs-on: ubuntu-latest
    needs: upload-artifact
    steps:
    - uses: actions/download-artifact@v4.1.8
      with:
        name: my-artifact
    - name: Display structure of downloaded files
      run: ls -R
    - run: cat myArtifact.txt
      
  upload-artifact:
    name: job to upload an artifact
    runs-on: ubuntu-latest
    steps:
      - run: docker info > myArtifact.txt
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: myArtifact.txt
